const ARQ_COMPONENTS = [
  {
    id: 'CMP-001',
    name: 'Button',
    purpose: 'Trigger a labelled action',
    renderer: 'button',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-002',
    name: 'Icon button',
    purpose: 'Trigger a compact action with an accessible name',
    renderer: 'icon-button',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-003',
    name: 'Split button',
    purpose: 'Offer a primary action and related menu',
    renderer: 'split-button',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-004',
    name: 'Top application bar',
    purpose: 'Show project identity and global actions',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-005',
    name: 'Tool rail',
    purpose: 'Expose stable tool categories and active tool',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-006',
    name: 'Context bar',
    purpose: 'Expose immediate controls for the active tool or selection',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-007',
    name: 'Status bar',
    purpose: 'Show units, snap, selection, save, sync and model health',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-008',
    name: 'Model tree',
    purpose: 'Navigate levels, views, sheets, imports and elements',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-009',
    name: 'Inspector',
    purpose: 'Edit and inspect selected object properties',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-010',
    name: 'Property row',
    purpose: 'Show label, value, inheritance and validation',
    renderer: 'property-row',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-011',
    name: 'Text field',
    purpose: 'Enter text',
    renderer: 'field',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-012',
    name: 'Numeric field',
    purpose: 'Enter unit-aware numeric values',
    renderer: 'field',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-013',
    name: 'Search field',
    purpose: 'Search pages, objects or commands',
    renderer: 'field',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-014',
    name: 'Select',
    purpose: 'Choose one option',
    renderer: 'select',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-015',
    name: 'Combobox',
    purpose: 'Search and choose an option',
    renderer: 'select',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-016',
    name: 'Checkbox',
    purpose: 'Toggle independent selection',
    renderer: 'checkbox',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-017',
    name: 'Radio group',
    purpose: 'Choose one exclusive option',
    renderer: 'radio',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-018',
    name: 'Switch',
    purpose: 'Toggle an immediate setting',
    renderer: 'toggle',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-019',
    name: 'Slider',
    purpose: 'Adjust a bounded continuous value',
    renderer: 'slider',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-020',
    name: 'Segmented control',
    purpose: 'Choose a compact mode',
    renderer: 'segmented',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-021',
    name: 'Tabs',
    purpose: 'Navigate peer sections',
    renderer: 'tabs',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-022',
    name: 'Menu',
    purpose: 'Show contextual actions',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-023',
    name: 'Context menu',
    purpose: 'Show pointer-context actions',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-024',
    name: 'Popover',
    purpose: 'Show non-modal contextual content',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-025',
    name: 'Tooltip',
    purpose: 'Explain a control or shortcut',
    renderer: 'tooltip',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-026',
    name: 'Dialog',
    purpose: 'Require focused confirmation or input',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-027',
    name: 'Drawer',
    purpose: 'Show secondary desktop content',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-028',
    name: 'Bottom sheet',
    purpose: 'Show secondary iPad portrait content',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-029',
    name: 'Toast',
    purpose: 'Announce transient result',
    renderer: 'toast',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-030',
    name: 'Banner',
    purpose: 'Show persistent page-level status',
    renderer: 'banner',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-031',
    name: 'Inline validation',
    purpose: 'Explain a field or object problem',
    renderer: 'inline-validation',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-032',
    name: 'Validation summary',
    purpose: 'List blocking problems',
    renderer: 'banner',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-033',
    name: 'Progress indicator',
    purpose: 'Show determinate or indeterminate work',
    renderer: 'progress',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-034',
    name: 'Skeleton',
    purpose: 'Reserve loading layout',
    renderer: 'skeleton',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-035',
    name: 'Empty state',
    purpose: 'Explain absence and next action',
    renderer: 'empty-state',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-036',
    name: 'Data table',
    purpose: 'Display sortable structured rows',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-037',
    name: 'List',
    purpose: 'Display ordered or filtered items',
    renderer: 'list',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-038',
    name: 'Tree item',
    purpose: 'Represent hierarchical content',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-039',
    name: 'Card',
    purpose: 'Summarise a project or template',
    renderer: 'card',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-040',
    name: 'Breadcrumb',
    purpose: 'Show hierarchical location',
    renderer: 'breadcrumb',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-041',
    name: 'Project switcher',
    purpose: 'Change active project',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-042',
    name: 'Workspace switcher',
    purpose: 'Change active workspace',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-043',
    name: 'User menu',
    purpose: 'Access account and sign-out actions',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-044',
    name: 'Presence avatar',
    purpose: 'Show collaborator identity and state',
    renderer: 'avatar',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-045',
    name: 'Permission selector',
    purpose: 'Assign a role',
    renderer: 'select',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-046',
    name: 'Share link control',
    purpose: 'Create and revoke controlled links',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-047',
    name: 'Command palette',
    purpose: 'Search actions and objects',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-048',
    name: 'Shortcut hint',
    purpose: 'Display a platform-aware shortcut',
    renderer: 'shortcut-hint',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-049',
    name: 'Canvas',
    purpose: 'Render and interact with plan, model or sheet',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-050',
    name: 'Canvas overlay',
    purpose: 'Host transient controls and warnings',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-051',
    name: 'Selection handle',
    purpose: 'Manipulate selected geometry',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-052',
    name: 'Selection outline',
    purpose: 'Show primary and secondary selection',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-053',
    name: 'Snap glyph',
    purpose: 'Show active snap type and source',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-054',
    name: 'Numeric overlay',
    purpose: 'Enter distance and angle during a command',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-055',
    name: 'View cube',
    purpose: 'Change 3D orientation',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-056',
    name: 'Zoom control',
    purpose: 'Fit and change view scale',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-057',
    name: 'Scale control',
    purpose: 'Show or select drawing scale',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-058',
    name: 'Minimap',
    purpose: 'Navigate a large plan later',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-059',
    name: 'Underlay control',
    purpose: 'Calibrate, lock and change opacity',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-060',
    name: 'Import dropzone',
    purpose: 'Accept supported files',
    renderer: 'dropzone',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-061',
    name: 'Import summary',
    purpose: 'Report preserved and unsupported content',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-062',
    name: 'Export options',
    purpose: 'Select format, scope and validation',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-063',
    name: 'Export summary',
    purpose: 'Report output and warnings',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-064',
    name: 'Comment pin',
    purpose: 'Anchor a comment to model or sheet',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-065',
    name: 'Comment thread',
    purpose: 'Discuss and resolve feedback',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-066',
    name: 'Issue card',
    purpose: 'Track an actionable issue',
    renderer: 'card',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-067',
    name: 'History timeline',
    purpose: 'Show revisions and operations',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-068',
    name: 'Revision badge',
    purpose: 'Show draft, review or issued state',
    renderer: 'badge',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-069',
    name: 'Compare legend',
    purpose: 'Explain added, modified and deleted objects',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-070',
    name: 'Model health indicator',
    purpose: 'Summarise warnings and errors',
    renderer: 'badge',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-071',
    name: 'Recovery panel',
    purpose: 'Explain recovered and incomplete work',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-072',
    name: 'Sync state',
    purpose: 'Distinguish local save from cloud sync',
    renderer: 'badge',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-073',
    name: 'Offline indicator',
    purpose: 'Show network-independent status',
    renderer: 'badge',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-074',
    name: 'Conflict resolver',
    purpose: 'Resolve incompatible operations',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-075',
    name: 'AI request field',
    purpose: 'Enter a bounded natural-language request',
    renderer: 'field',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-076',
    name: 'AI proposal panel',
    purpose: 'Preview intent, assumptions and operations',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-077',
    name: 'AI operation row',
    purpose: 'Show one proposed typed change',
    renderer: 'list',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-078',
    name: 'Filter bar',
    purpose: 'Filter lists, warnings or issues',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-079',
    name: 'Tag or status badge',
    purpose: 'Show compact labelled status',
    renderer: 'badge',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-080',
    name: 'Pattern swatch',
    purpose: 'Select a monochrome pattern',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-081',
    name: 'File row',
    purpose: 'Show file name, status, size and actions',
    renderer: 'list',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-082',
    name: 'Job progress',
    purpose: 'Show import or export stage and cancellation',
    renderer: 'progress',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-083',
    name: 'Support bundle control',
    purpose: 'Create diagnostics with explicit consent',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
  {
    id: 'CMP-084',
    name: 'Coachmark',
    purpose: 'Teach a contextual onboarding step',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover where pointer exists',
      'Focus visible',
      'Active or pressed',
      'Disabled with reason where useful',
      'Loading where applicable',
      'Invalid where applicable',
      'Selected where applicable',
    ],
  },
];
