// Data for the component test harness (component-harness/index.html + harness.js).
// Regenerated from docs/components/COMPONENT-MAP.csv and each component's own
// CMP-XXX doc (ARQ-190) - states here must always match the doc's "Required
// states" section, not drift independently. See scripts/gen-component-docs.mjs
// (or its scratchpad equivalent) for the generator.
const ARQ_COMPONENTS = [
  {
    id: 'CMP-001',
    name: 'Button',
    purpose: 'Trigger a labelled action',
    renderer: 'button',
    states: [
      'Default',
      'Hover',
      'Focus visible',
      'Active/pressed',
      'Disabled with reason',
      'Loading (label replaced by spinner, width preserved)',
    ],
  },
  {
    id: 'CMP-002',
    name: 'Icon button',
    purpose: 'Trigger a compact action with an accessible name',
    renderer: 'icon-button',
    states: [
      'Default',
      'Hover',
      'Focus visible',
      'Active/pressed',
      'Disabled with reason',
      'Selected (toggle-style icon buttons)',
    ],
  },
  {
    id: 'CMP-003',
    name: 'Split button',
    purpose: 'Offer a primary action and related menu',
    renderer: 'split-button',
    states: [
      'Default',
      'Hover (per segment)',
      'Focus visible (per segment)',
      'Active/pressed (per segment)',
      'Disabled with reason',
      'Menu open',
    ],
  },
  {
    id: 'CMP-004',
    name: 'Top application bar',
    purpose: 'Show project identity and global actions',
    renderer: 'placeholder',
    states: [
      'Default',
      'Title in edit mode',
      'Sync status: saved/saving/offline/conflict',
      'Narrow-viewport collapsed (icons only)',
    ],
  },
  {
    id: 'CMP-005',
    name: 'Tool rail',
    purpose: 'Expose stable tool categories and active tool',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover',
      'Focus visible',
      'Active tool (pressed + selected)',
      'Disabled (tool unavailable in current mode)',
    ],
  },
  {
    id: 'CMP-006',
    name: 'Context bar',
    purpose: 'Expose immediate controls for the active tool or selection',
    renderer: 'placeholder',
    states: [
      'Empty (no tool/selection - hidden or shows a hint)',
      'Populated for active tool',
      'Populated for active selection',
      'Disabled sub-controls where a setting does not apply',
    ],
  },
  {
    id: 'CMP-007',
    name: 'Status bar',
    purpose: 'Show units, snap, selection, save, sync and model health',
    renderer: 'placeholder',
    states: [
      'Default',
      'Selection empty vs populated',
      'Snap active vs inactive',
      'Sync: saved/saving/offline/conflict',
      'Model health: healthy/warnings/errors',
    ],
  },
  {
    id: 'CMP-008',
    name: 'Model tree',
    purpose: 'Navigate levels, views, sheets, imports and elements',
    renderer: 'placeholder',
    states: [
      'Default',
      'Filtered (matches highlighted, non-matches collapsed)',
      'Empty (no project content yet)',
      'Node selected/multi-selected',
      'Node loading (large import still staging)',
    ],
  },
  {
    id: 'CMP-009',
    name: 'Inspector',
    purpose: 'Edit and inspect selected object properties',
    renderer: 'placeholder',
    states: [
      'Empty (nothing selected)',
      'Single selection',
      'Multi-selection with mixed values',
      'Read-only (no permission to edit)',
    ],
  },
  {
    id: 'CMP-010',
    name: 'Property row',
    purpose: 'Show label, value, inheritance and validation',
    renderer: 'property-row',
    states: [
      'Default (own value)',
      'Inherited (from type/template, not overridden)',
      'Overridden (was inherited, now has its own value)',
      'Invalid',
      'Read-only',
    ],
  },
  {
    id: 'CMP-011',
    name: 'Text field',
    purpose: 'Enter text',
    renderer: 'field',
    states: ['Default', 'Focus', 'Filled', 'Disabled with reason', 'Invalid', 'Read-only'],
  },
  {
    id: 'CMP-012',
    name: 'Numeric field',
    purpose: 'Enter unit-aware numeric values',
    renderer: 'field',
    states: [
      'Default',
      'Focus (raw editable value shown)',
      'Blurred/committed (formatted with unit)',
      'Disabled with reason',
      'Invalid (out of range or unparseable)',
    ],
  },
  {
    id: 'CMP-013',
    name: 'Search field',
    purpose: 'Search pages, objects or commands',
    renderer: 'field',
    states: [
      'Empty',
      'Typing (debounced)',
      'Has results',
      'No results found',
      'Disabled with reason',
    ],
  },
  {
    id: 'CMP-014',
    name: 'Select',
    purpose: 'Choose one option',
    renderer: 'select',
    states: ['Default (closed)', 'Open', 'Focus', 'Disabled with reason', 'Invalid'],
  },
  {
    id: 'CMP-015',
    name: 'Combobox',
    purpose: 'Search and choose an option',
    renderer: 'select',
    states: [
      'Empty',
      'Typing (filtering)',
      'Open with suggestions',
      'No matches (optionally offers "create new")',
      'Selected',
      'Disabled with reason',
      'Invalid',
    ],
  },
  {
    id: 'CMP-016',
    name: 'Checkbox',
    purpose: 'Toggle independent selection',
    renderer: 'checkbox',
    states: [
      'Unchecked',
      'Checked',
      'Indeterminate (mixed children/partial selection)',
      'Focus visible',
      'Disabled with reason',
      'Invalid',
    ],
  },
  {
    id: 'CMP-017',
    name: 'Radio group',
    purpose: 'Choose one exclusive option',
    renderer: 'radio',
    states: [
      'Default (one option selected)',
      'Focus visible (on the focused option)',
      'Disabled with reason (whole group or a single option)',
      'Invalid (group-level, e.g. required but unanswered)',
    ],
  },
  {
    id: 'CMP-018',
    name: 'Switch',
    purpose: 'Toggle an immediate setting',
    renderer: 'toggle',
    states: [
      'Off',
      'On',
      'Focus visible',
      'Disabled with reason',
      'Transitioning (mid-animation, non-interactive)',
    ],
  },
  {
    id: 'CMP-019',
    name: 'Slider',
    purpose: 'Adjust a bounded continuous value',
    renderer: 'slider',
    states: ['Default', 'Focus visible', 'Dragging (thumb active)', 'Disabled with reason'],
  },
  {
    id: 'CMP-020',
    name: 'Segmented control',
    purpose: 'Choose a compact mode',
    renderer: 'segmented',
    states: [
      'Default',
      'Hover (per segment)',
      'Focus visible (per segment)',
      'Selected segment',
      'Disabled with reason (whole control or one segment)',
    ],
  },
  {
    id: 'CMP-021',
    name: 'Tabs',
    purpose: 'Navigate peer sections',
    renderer: 'tabs',
    states: [
      'Default',
      'Focus visible (on the focused tab)',
      'Selected tab',
      'Disabled tab with reason',
    ],
  },
  {
    id: 'CMP-022',
    name: 'Menu',
    purpose: 'Show contextual actions',
    renderer: 'placeholder',
    states: [
      'Closed',
      'Open',
      'Item focused',
      'Item disabled with reason',
      'Submenu open (nested menu)',
    ],
  },
  {
    id: 'CMP-023',
    name: 'Context menu',
    purpose: 'Show pointer-context actions',
    renderer: 'placeholder',
    states: [
      'Closed',
      'Open at pointer/touch position',
      'Item focused',
      'Item disabled with reason',
    ],
  },
  {
    id: 'CMP-024',
    name: 'Popover',
    purpose: 'Show non-modal contextual content',
    renderer: 'placeholder',
    states: ['Closed', 'Open', 'Focus within'],
  },
  {
    id: 'CMP-025',
    name: 'Tooltip',
    purpose: 'Explain a control or shortcut',
    renderer: 'tooltip',
    states: ['Hidden', 'Visible (on hover or focus)'],
  },
  {
    id: 'CMP-026',
    name: 'Dialog',
    purpose: 'Require focused confirmation or input',
    renderer: 'placeholder',
    states: [
      'Closed',
      'Open',
      'Open with a validation error blocking its primary action',
      'Busy (primary action in progress)',
    ],
  },
  {
    id: 'CMP-027',
    name: 'Drawer',
    purpose: 'Show secondary desktop content',
    renderer: 'placeholder',
    states: ['Closed', 'Open', 'Resizing (if the drawer supports a draggable edge)'],
  },
  {
    id: 'CMP-028',
    name: 'Bottom sheet',
    purpose: 'Show secondary iPad portrait content',
    renderer: 'placeholder',
    states: [
      'Closed',
      'Peek (partially visible, collapsed)',
      'Open (fully expanded)',
      'Dragging (mid-gesture)',
    ],
  },
  {
    id: 'CMP-029',
    name: 'Toast',
    purpose: 'Announce transient result',
    renderer: 'toast',
    states: ['Visible', 'Visible with action', 'Dismissing (exit animation)'],
  },
  {
    id: 'CMP-030',
    name: 'Banner',
    purpose: 'Show persistent page-level status',
    renderer: 'banner',
    states: ['Visible (info/warning/error severity)', 'Dismissed (if dismissable)'],
  },
  {
    id: 'CMP-031',
    name: 'Inline validation',
    purpose: 'Explain a field or object problem',
    renderer: 'inline-validation',
    states: ['Hidden (valid)', 'Visible (invalid)'],
  },
  {
    id: 'CMP-032',
    name: 'Validation summary',
    purpose: 'List blocking problems',
    renderer: 'banner',
    states: ['Hidden (no blocking problems)', 'Visible with N problems'],
  },
  {
    id: 'CMP-033',
    name: 'Progress indicator',
    purpose: 'Show determinate or indeterminate work',
    renderer: 'progress',
    states: [
      'Determinate (known percentage)',
      'Indeterminate (unknown duration)',
      'Complete',
      'Failed',
    ],
  },
  {
    id: 'CMP-034',
    name: 'Skeleton',
    purpose: 'Reserve loading layout',
    renderer: 'skeleton',
    states: ['Visible (loading)', 'Replaced by real content'],
  },
  {
    id: 'CMP-035',
    name: 'Empty state',
    purpose: 'Explain absence and next action',
    renderer: 'empty-state',
    states: ['Visible (no content yet)', 'Visible (no results after a filter/search)'],
  },
  {
    id: 'CMP-036',
    name: 'Data table',
    purpose: 'Display sortable structured rows',
    renderer: 'placeholder',
    states: [
      'Default',
      'Sorted (ascending/descending per column)',
      'Row hover',
      'Row selected',
      'Empty (delegates to CMP-035)',
      'Loading (delegates to CMP-034/033)',
    ],
  },
  {
    id: 'CMP-037',
    name: 'List',
    purpose: 'Display ordered or filtered items',
    renderer: 'list',
    states: [
      'Default',
      'Item hover',
      'Item selected',
      'Filtered (subset visible)',
      'Empty (delegates to CMP-035)',
    ],
  },
  {
    id: 'CMP-038',
    name: 'Tree item',
    purpose: 'Represent hierarchical content',
    renderer: 'placeholder',
    states: [
      'Collapsed (has children)',
      'Expanded',
      'Leaf (no children, no disclosure control)',
      'Selected/multi-selected',
      'Focus visible',
    ],
  },
  {
    id: 'CMP-039',
    name: 'Card',
    purpose: 'Summarise a project or template',
    renderer: 'card',
    states: [
      'Default',
      'Hover',
      'Focus visible',
      'Selected (in a multi-select grid)',
      'Syncing/offline (delegates to CMP-072/CMP-073)',
    ],
  },
  {
    id: 'CMP-040',
    name: 'Breadcrumb',
    purpose: 'Show hierarchical location',
    renderer: 'breadcrumb',
    states: ['Default', 'Truncated (collapses middle segments on narrow width)'],
  },
  {
    id: 'CMP-041',
    name: 'Project switcher',
    purpose: 'Change active project',
    renderer: 'placeholder',
    states: [
      'Closed',
      'Open',
      'Filtering (many projects)',
      'Loading (project list still fetching)',
    ],
  },
  {
    id: 'CMP-042',
    name: 'Workspace switcher',
    purpose: 'Change active workspace',
    renderer: 'placeholder',
    states: ['Closed', 'Open', 'Loading (workspace list still fetching)'],
  },
  {
    id: 'CMP-043',
    name: 'User menu',
    purpose: 'Access account and sign-out actions',
    renderer: 'placeholder',
    states: ['Closed', 'Open'],
  },
  {
    id: 'CMP-044',
    name: 'Presence avatar',
    purpose: 'Show collaborator identity and state',
    renderer: 'avatar',
    states: ['Online', 'Idle', 'Offline', 'Focus visible (when interactive, e.g. in CMP-043)'],
  },
  {
    id: 'CMP-045',
    name: 'Permission selector',
    purpose: 'Assign a role',
    renderer: 'select',
    states: [
      'Default',
      'Open (choosing a new role)',
      'Disabled with reason (e.g. cannot demote the last owner)',
    ],
  },
  {
    id: 'CMP-046',
    name: 'Share link control',
    purpose: 'Create and revoke controlled links',
    renderer: 'placeholder',
    states: [
      'No link exists yet',
      'Link exists',
      'Just copied (transient confirmation)',
      'Revoking (confirm step)',
    ],
  },
  {
    id: 'CMP-047',
    name: 'Command palette',
    purpose: 'Search actions and objects',
    renderer: 'placeholder',
    states: [
      'Closed',
      'Open, empty query (recent/suggested commands)',
      'Open, typing (filtered results)',
      'No results',
      'Result focused',
    ],
  },
  {
    id: 'CMP-048',
    name: 'Shortcut hint',
    purpose: 'Display a platform-aware shortcut',
    renderer: 'shortcut-hint',
    states: ['Visible'],
  },
  {
    id: 'CMP-049',
    name: 'Canvas',
    purpose: 'Render and interact with plan, model or sheet',
    renderer: 'placeholder',
    states: [
      'Default (idle)',
      'Panning',
      'Zooming',
      'Active drawing command in progress',
      'Selection active',
    ],
  },
  {
    id: 'CMP-050',
    name: 'Canvas overlay',
    purpose: 'Host transient controls and warnings',
    renderer: 'placeholder',
    states: ['Empty (nothing to show)', 'Showing one or more transient controls/warnings'],
  },
  {
    id: 'CMP-051',
    name: 'Selection handle',
    purpose: 'Manipulate selected geometry',
    renderer: 'placeholder',
    states: [
      'Default',
      'Hover',
      'Dragging',
      'Snapped (delegates to CMP-053 Snap glyph while dragging)',
    ],
  },
  {
    id: 'CMP-052',
    name: 'Selection outline',
    purpose: 'Show primary and secondary selection',
    renderer: 'placeholder',
    states: [
      'Unselected (not rendered)',
      'Primary selection',
      'Secondary/additional selection (multi-select)',
    ],
  },
  {
    id: 'CMP-053',
    name: 'Snap glyph',
    purpose: 'Show active snap type and source',
    renderer: 'placeholder',
    states: ['Hidden (no active snap)', 'Visible per snap type (one glyph shape per type)'],
  },
  {
    id: 'CMP-054',
    name: 'Numeric overlay',
    purpose: 'Enter distance and angle during a command',
    renderer: 'placeholder',
    states: [
      'Hidden (no active command)',
      'Visible, tracking pointer',
      'Visible, value being typed (locks that axis to the typed value)',
    ],
  },
  {
    id: 'CMP-055',
    name: 'View cube',
    purpose: 'Change 3D orientation',
    renderer: 'placeholder',
    states: ['Default', 'Hover (per face/edge/corner)', 'Active drag (free rotate)'],
  },
  {
    id: 'CMP-056',
    name: 'Zoom control',
    purpose: 'Fit and change view scale',
    renderer: 'placeholder',
    states: ['Default', 'At minimum zoom', 'At maximum zoom'],
  },
  {
    id: 'CMP-057',
    name: 'Scale control',
    purpose: 'Show or select drawing scale',
    renderer: 'placeholder',
    states: ['Default', 'Open (choosing a new scale)', 'Custom scale entered'],
  },
  {
    id: 'CMP-058',
    name: 'Minimap',
    purpose: 'Navigate a large plan later',
    renderer: 'placeholder',
    states: ['Default', 'Dragging the viewport rectangle (panning the main view)'],
  },
  {
    id: 'CMP-059',
    name: 'Underlay control',
    purpose: 'Calibrate, lock and change opacity',
    renderer: 'placeholder',
    states: [
      'Default (unlocked)',
      'Locked (position/scale fixed)',
      'Calibrating (mid-calibration flow)',
    ],
  },
  {
    id: 'CMP-060',
    name: 'Import dropzone',
    purpose: 'Accept supported files',
    renderer: 'dropzone',
    states: [
      'Idle',
      'Drag-over (valid file type)',
      'Drag-over (invalid file type)',
      'Uploading/processing',
    ],
  },
  {
    id: 'CMP-061',
    name: 'Import summary',
    purpose: 'Report preserved and unsupported content',
    renderer: 'placeholder',
    states: [
      'Success (fully preserved)',
      'Partial (some content approximated/attached/ignored)',
      'Failed',
    ],
  },
  {
    id: 'CMP-062',
    name: 'Export options',
    purpose: 'Select format, scope and validation',
    renderer: 'placeholder',
    states: ['Default', 'Validating', 'Blocked (validation problems exist)', 'Ready to export'],
  },
  {
    id: 'CMP-063',
    name: 'Export summary',
    purpose: 'Report output and warnings',
    renderer: 'placeholder',
    states: ['Success (no warnings)', 'Success with warnings', 'Failed'],
  },
  {
    id: 'CMP-064',
    name: 'Comment pin',
    purpose: 'Anchor a comment to model or sheet',
    renderer: 'placeholder',
    states: [
      'Unresolved',
      'Resolved',
      'Hover (preview)',
      'Selected (opens CMP-065 Comment thread)',
    ],
  },
  {
    id: 'CMP-065',
    name: 'Comment thread',
    purpose: 'Discuss and resolve feedback',
    renderer: 'placeholder',
    states: ['Open (unresolved)', 'Resolved', 'Composing a reply'],
  },
  {
    id: 'CMP-066',
    name: 'Issue card',
    purpose: 'Track an actionable issue',
    renderer: 'card',
    states: ['Open', 'In progress', 'Resolved', 'Overdue (if a due date exists and has passed)'],
  },
  {
    id: 'CMP-067',
    name: 'History timeline',
    purpose: 'Show revisions and operations',
    renderer: 'placeholder',
    states: [
      'Default',
      'Entry expanded (showing constituent operations)',
      'Loading more (older history, paginated)',
    ],
  },
  {
    id: 'CMP-068',
    name: 'Revision badge',
    purpose: 'Show draft, review or issued state',
    renderer: 'badge',
    states: ['Draft', 'In review', 'Issued'],
  },
  {
    id: 'CMP-069',
    name: 'Compare legend',
    purpose: 'Explain added, modified and deleted objects',
    renderer: 'placeholder',
    states: ['Visible alongside an active compare view'],
  },
  {
    id: 'CMP-070',
    name: 'Model health indicator',
    purpose: 'Summarise warnings and errors',
    renderer: 'badge',
    states: ['Healthy (no issues)', 'Warnings present', 'Errors present'],
  },
  {
    id: 'CMP-071',
    name: 'Recovery panel',
    purpose: 'Explain recovered and incomplete work',
    renderer: 'placeholder',
    states: ['Visible after a recovery event', 'Acknowledged/dismissed'],
  },
  {
    id: 'CMP-072',
    name: 'Sync state',
    purpose: 'Distinguish local save from cloud sync',
    renderer: 'badge',
    states: ['Saved locally, not yet synced', 'Syncing', 'Synced', 'Sync error'],
  },
  {
    id: 'CMP-073',
    name: 'Offline indicator',
    purpose: 'Show network-independent status',
    renderer: 'badge',
    states: ['Online (hidden or neutral)', 'Offline'],
  },
  {
    id: 'CMP-074',
    name: 'Conflict resolver',
    purpose: 'Resolve incompatible operations',
    renderer: 'placeholder',
    states: ['Unresolved conflict presented', 'Previewing a chosen resolution', 'Resolved'],
  },
  {
    id: 'CMP-075',
    name: 'AI request field',
    purpose: 'Enter a bounded natural-language request',
    renderer: 'field',
    states: ['Empty', 'Typing', 'Submitted (processing)', 'Disabled with reason'],
  },
  {
    id: 'CMP-076',
    name: 'AI proposal panel',
    purpose: 'Preview intent, assumptions and operations',
    renderer: 'placeholder',
    states: [
      'Proposing (loading)',
      'Ready for review',
      'Partially accepted (some operations accepted, others rejected)',
      'Fully accepted',
      'Fully rejected',
    ],
  },
  {
    id: 'CMP-077',
    name: 'AI operation row',
    purpose: 'Show one proposed typed change',
    renderer: 'list',
    states: ['Pending review', 'Accepted', 'Rejected'],
  },
  {
    id: 'CMP-078',
    name: 'Filter bar',
    purpose: 'Filter lists, warnings or issues',
    renderer: 'placeholder',
    states: [
      'No filters active',
      'One or more filters active',
      'Filter combination yields zero results (delegates to CMP-035)',
    ],
  },
  {
    id: 'CMP-079',
    name: 'Tag or status badge',
    purpose: 'Show compact labelled status',
    renderer: 'badge',
    states: ['Default (per status/tag value)'],
  },
  {
    id: 'CMP-080',
    name: 'Pattern swatch',
    purpose: 'Select a monochrome pattern',
    renderer: 'placeholder',
    states: ['Default', 'Hover', 'Focus visible', 'Selected'],
  },
  {
    id: 'CMP-081',
    name: 'File row',
    purpose: 'Show file name, status, size and actions',
    renderer: 'list',
    states: [
      'Default',
      'Hover',
      'Processing (import/export in progress, delegates to CMP-082)',
      'Error',
    ],
  },
  {
    id: 'CMP-082',
    name: 'Job progress',
    purpose: 'Show import or export stage and cancellation',
    renderer: 'progress',
    states: [
      'Queued',
      'In progress (per real pipeline stage)',
      'Cancelling',
      'Cancelled',
      'Complete',
      'Failed',
    ],
  },
  {
    id: 'CMP-083',
    name: 'Support bundle control',
    purpose: 'Create diagnostics with explicit consent',
    renderer: 'placeholder',
    states: ['Awaiting consent', 'Creating', 'Ready to share/download'],
  },
  {
    id: 'CMP-084',
    name: 'Coachmark',
    purpose: 'Teach a contextual onboarding step',
    renderer: 'placeholder',
    states: ['Visible (current step)', 'Dismissed'],
  },
];
