import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Loads the dependency SBOM generated by scripts/check-dependency-licences.mjs
 * (ARQ-016). The file is generated - not committed - so the loader walks up
 * from this module to the repository root, which keeps it working both from
 * src/ under vitest and from dist-build/ at build time.
 */

export interface SbomPackage {
  readonly name: string;
  readonly version: string;
  readonly licence: string;
}

export interface Sbom {
  readonly generatedAt: string;
  readonly packageCount: number;
  readonly packages: readonly SbomPackage[];
}

export function findRepoRoot(startDir: string): string {
  let dir = startDir;
  for (let i = 0; i < 10; i += 1) {
    try {
      readFileSync(join(dir, 'pnpm-workspace.yaml'));
      return dir;
    } catch {
      const parent = dirname(dir);
      if (parent === dir) {
        break;
      }
      dir = parent;
    }
  }
  throw new Error(`Repository root not found above ${startDir}`);
}

export function loadSbom(): Sbom {
  const here = dirname(fileURLToPath(import.meta.url));
  const root = findRepoRoot(here);
  const rawSbom = readFileSync(join(root, 'dependency-sbom.json'), 'utf8');
  const parsed = JSON.parse(rawSbom) as Sbom;
  if (!Array.isArray(parsed.packages) || typeof parsed.packageCount !== 'number') {
    throw new Error('dependency-sbom.json does not have the expected shape');
  }
  return parsed;
}

/** Groups SBOM packages by licence, most-used licence first. */
export function groupByLicence(sbom: Sbom): readonly {
  readonly licence: string;
  readonly packages: readonly SbomPackage[];
}[] {
  const groups = new Map<string, SbomPackage[]>();
  for (const pkg of sbom.packages) {
    const existing = groups.get(pkg.licence);
    if (existing === undefined) {
      groups.set(pkg.licence, [pkg]);
    } else {
      existing.push(pkg);
    }
  }
  return [...groups.entries()]
    .sort((a, b) => b[1].length - a[1].length || a[0].localeCompare(b[0]))
    .map(([licence, packages]) => ({
      licence,
      packages: [...packages].sort((a, b) => a.name.localeCompare(b.name)),
    }));
}
